/**
 * @fileOverview Centralized constants for the EBENESAID platform.
 * Used to ensure consistency across Registration, Settings, and AI flows.
 */

export const UNIVERSITIES = [
  { id: "baltic-international-academy", name: "Baltic International Academy" },
  { id: "daugavpils-university", name: "Daugavpils University" },
  { id: "ekonomikas-un-kulturas-augstskola", name: "Ekonomikas un Kulturas Augstskola" },
  { id: "isma", name: "ISMA University of Applied Sciences" },
  { id: "latvian-academy-of-culture", name: "Latvian Academy of Culture" },
  { id: "latvian-academy-of-music", name: "Latvian Academy of Music" },
  { id: "latvian-academy-of-sport-education", name: "Latvian Academy of Sport Education" },
  { id: "latvian-maritime-academy", name: "Latvian Maritime Academy" },
  { id: "latvian-university-of-life-sciences-and-technologies", name: "Latvian University of Life Sciences and Technologies" },
  { id: "liepaja-university", name: "Liepaja University" },
  { id: "rezekne-academy-of-technologies", name: "Rezekne Academy of Technologies" },
  { id: "riseba", name: "RISEBA University of Applied Sciences" },
  { id: "riga-aeronautical-institute", name: "Riga Aeronautical Institute" },
  { id: "riga-business-school", name: "Riga Business School" },
  { id: "riga-stradins-university", name: "Riga Stradins University" },
  { id: "riga-technical-university", name: "Riga Technical University" },
  { id: "sse-riga", name: "SSE Riga" },
  { id: "transport-and-telecommunication-institute", name: "Transport and Telecommunication Institute" },
  { id: "turiba-university", name: "Turiba University" },
  { id: "university-of-latvia", name: "University of Latvia" },
  { id: "ventspils-university-of-applied-sciences", name: "Ventspils University of Applied Sciences" },
  { id: "vidzeme-university-of-applied-sciences", name: "Vidzeme University of Applied Sciences" }
];

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const NATIONALITIES = COUNTRIES;
